### ISSUE TITLE
unity 2019.3.8f1 android 64bitに対応するとクライアント初期化でエラー 調査お願いします

### ISSUE THREAD

**Issue by sasuraipenguin** [gs2io/gs2-feedback#90]
最近、google playにアプリをアップロードするには、android 64bitに対応する必要がでてきた為、
Player SettingsのPlayer アンドロイド Other Settings - Configurationで、以下のScripting BackendをMonoから、IL2CPPに変更する必要がでてきました。

この状態でBuildし、実機で実行すると、最初のクライアントの初期化
            var current = profile.Initialize(
                r => { asyncResult = r; }
            );
で、Gs2.Core.Exception.UnknpwnException: JSON parsing error: DBvRm.......
というエラーが出てしまいます。
Monoに戻すと、正常に動作します。

調査お願いいたします。

![image](https://user-images.githubusercontent.com/38824767/93903203-5639a800-fd33-11ea-9cfa-685fe6c694dd.png)

**Comment by imatakeharuhiko** [comment]
ご迷惑をおかけしており申し訳ございません。
ご提示の環境に揃えて弊社で再現を試みたのですが、再現できておりません。
エラーの発生した詳細な時刻や最小サンプルを頂戴することはできませんでしょうか？

**Comment by sasuraipenguin** [comment]
返答が遅くなり申し訳ございません。
調査進めて頂き、有難うございます。

再現しないとのことでしたが、念のため確認させてください。
本件ですが、unity上は正常に動きますが、実機側で動かないという内容になります。
実機は、android7.1.1 arrows04(スマホ)、android8.0.0 HUAWEI MediaPad T5(タブレット)で現象確認しました(それ以外では試せていません)
実機側で再現しませんでしょうか。

詳細な時刻ですが、2020/10/6 22:25 です。

最小コードは以下になります。

using Gs2.Core;
using Gs2.Unity.Gs2Account.Model;
using Gs2.Unity.Gs2Account.Result;
using Gs2.Unity.Gs2Datastore.Result;
using Gs2.Unity.Gs2Experience.Model;    
using Gs2.Unity.Gs2Experience.Result;
using Gs2.Unity.Gs2Inventory.Result;
using Gs2.Unity.Gs2Quest.Model;
using Gs2.Unity.Gs2Quest.Result;
using Gs2.Unity.Gs2Stamina.Model;
using Gs2.Unity.Gs2Stamina.Result;
using Gs2.Unity.Util;
using SimpleSQL;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Gs2Account : MonoBehaviour
{
    // GS2-Identifier で発行したクライアントID
    public string clientId;

    // GS2-Identifier で発行したクライアントシークレット
    public string clientSecret;

    // アカウントを作成する GS2-Account のネームスペース名
    public string accountNamespaceName;

    // アカウントの認証結果に付与する署名を計算するのに使用する暗号鍵
    public string accountEncryptionKeyId;

    void Awake()
    {
    }

    public void Execute()
    {
        StartCoroutine(CreateAndLoginActionTest());
    }

    public IEnumerator CreateAndLoginActionTest()
    {
        // GS2 SDK のクライアントを初期化

        Debug.Log("GS2 SDK のクライアントを初期化");

        var profile = new Gs2.Unity.Util.Profile(
            clientId: clientId,
            clientSecret: clientSecret,
            reopener: new Gs2BasicReopener()
        );

        {
            AsyncResult<object> asyncResult = null;

            var current = profile.Initialize(
                r => { asyncResult = r; }
            );

            yield return current;

            // コルーチンの実行が終了した時点で、コールバックは必ず呼ばれています

            // クライアントの初期化に失敗した場合は終了
            if (asyncResult.Error != null)
            {
                Define.OnError(asyncResult.Error);
                yield break;
            }
        }
    }
}

**Comment by imatakeharuhiko** [comment]
こちらこそご返答が遅くなって申し訳ありませんでした。
当方では API レベル等もそろえたうえで Pixel 3 上での確認を行いましたが、問題は発生しておりません。
メッセージを見る限り、サーバから応答した JSON のパース時にエラーとなっているようですので、お知らせいただいた時刻のサーバ応答なども含めて改めて確認いたします。

**Comment by sasuraipenguin** [comment]
お手数かけますが、よろしくお願いいたします。

**Comment by imatakeharuhiko** [comment]
ご指定の時刻周辺のサーバのログを確認したのですが、それらしいリクエストが確認できませんでした。

> Gs2.Core.Exception.UnknpwnException: JSON parsing error: DBvRm.......

のエラーの省略部分がわかるとありがたいのですが、頂戴できますでしょうか？
もし表示が切れてしまっているようでしたら、 Scripts/Runtime/Sdk/Gs2/Core/Net 下に4か所ある "JSON parsing error: \n" という文字列で例外を構築している箇所からメッセージを取り出していただくことは可能でしょうか？

**Comment by sasuraipenguin** [comment]
![Screenshot_20201007-140744](https://user-images.githubusercontent.com/38824767/95289839-bccbd380-08a6-11eb-948f-c3b3a2037f2d.png)

すみません、logの取り方がすぐにわからず、スクリーンショットを添付させていただきましたが、こちらではどうでしょうか
14:04:22 にも実行しています。

**Comment by sasuraipenguin** [comment]
申し訳ございません。最初に報告したログと少し違いました

**Comment by imatakeharuhiko** [comment]
ご調査ありがとうございます。
応答を見る限り正常で、適切な JSON が返っているように見受けられます。
また、やはりこちらでは発生しておりません。

現在、該当のエラーを出している箇所は

```
	        catch (System.Exception)
	        {
		        Error = new UnknownException("JSON parsing error: \n" + message);
	        }
```

のような実装（箇所によって微妙に異なります）になっていると思うのですが、こちらを

```
	        catch (System.Exception e)
	        {
		        Error = new UnknownException($"{e.Message}\n{e.StackTrace}");
	        }
```

と変えて出力を確認いただくことは可能でしょうか？

**Comment by sasuraipenguin** [comment]
![Screenshot_20201007-215732](https://user-images.githubusercontent.com/38824767/95333977-74cda080-08e8-11eb-8991-3bffc903bc34.png)
このようになりました

**Comment by imatakeharuhiko** [comment]
ご調査ありがとうございました。
内容を拝見すると、非明示的に利用されるコードが最適化によってデッドストリップされているのではないかと思われます。
SDK のバージョンはいくつをお使いでしょうか？
Ver. 2020.7.2 でこの問題に対処を入れておりまして、それより古い SDK をお使いでしたら、 SDK を更新して問題が解消するか、お試しいただけないでしょうか。

**Comment by sasuraipenguin** [comment]
Ver. 2020.6.6でした。
色々調査頂きありがとうございました。解決しました。packagesのupdate自体を知らなかったです・・。
10.1にupdateして、エラーなく動くようになりました。

**Comment by imatakeharuhiko** [comment]
ご確認ありがとうございます。
無事に動いたようで何よりでした。
こちらこそ早くに気づけず、お手数をおかけしてしまい申し訳ありませんでした。
