### ISSUE TITLE
WebSocketSharp のDLLが Photon のDLLと衝突する

### ISSUE THREAD

**Issue by sacchy** [gs2io/gs2-feedback#91]
以前に対応して頂いたのですが未だ解決できていないようです。

◆動作環境
Unity2019.3.13f1
gs2-unity-installer_2020.5.1.unitypackageを利用

◆ログ一部
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name websocket-sharp.dll included or the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: 
Assets/Photon/PhotonLibs/WebSocket/websocket-sharp.dll
D:/xxx/app/Library/PackageCache/io.gs2.unity.sdk@2020.9.1/Plugins/websocket-sharp.dll

◆その他
メニューにGS2の項目が表示されません

**Comment by niwa-kazutomo** [comment]
2020.9.2 でDLLのファイル名を変更しております。ご確認ください。
